// unik is a code preprocessor that replaces macro calls with sequential integers.
//
// It scans .go files in the specified directory (without recursing into subdirectories)
// for patterns like MACRO(integer) and replaces them with MACRO(1), MACRO(2), etc.
// Useful for generating unique identifiers in code.
//
// The macro must be declared in the target package as a type alias for the code to compile:
//   type __FILELINE__ = uint  // or int, uint64, etc.
//
// Examples:
//   # Replace all __FILELINE__(any_number) with sequential numbers in current dir
//   unik
//
//   # Use custom macro name and directory (no subdirectory recursion)
//   unik -macro UNIQUE -dir ./src
//
//   # Verbose output showing processing details
//   unik -v
//
//   # Use with go generate - add this comment in your .go file:
//   //go:generate unik -dir . -macro ID
//
// The counting starts at 1 and increments globally across all processed files.
// Integer literals can be decimal, binary (0b101), octal (0o755), or hex (0xFF).
// Only processes .go files directly in the specified directory, not subdirectories.

package main

import (
	"flag"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"regexp"
)

const intLiteral = `([0-9]+(_[0-9]+)*|0b[01]+(_[01]+)*|0o[0-7]+(_[0-7]+)*|0x[0-9a-fA-F]+(_[0-9a-fA-F]+)*)`

const usageFmt = `Command Usage: %[1]s [OPTIONS]
  code preprocessor that replaces "macros" of form NAME(integer) by NAME(1), NAME(2)...

OPTIONS
-------
`

// FileChange represents a file modification with its path and new content.
type FileChange struct {
	path    string
	content string
}

// Cmd holds command line options for the unik processor.
type Cmd struct {
	prog    string
	dir     string
	macro   string
	verbose bool
}

func parseFlags(progname string, args []string) (*Cmd, error) {
	cmd := Cmd{prog: filepath.Base(progname), dir: ".", macro: "__FILELINE__"}

	flags := flag.NewFlagSet(progname, flag.ContinueOnError)

	flags.Usage = func() {
		fmt.Fprintf(os.Stderr, usageFmt, cmd.prog)
		flags.PrintDefaults()
	}

	flags.Func("dir", `Directory to process (default ".")`, func(s string) error {
		cmd.dir = filepath.Clean(s)
		info, err := os.Stat(cmd.dir)
		if nil != err {
			return err
		}
		if !info.IsDir() {
			return fmt.Errorf("%s is not a directory", cmd.dir)
		}

		return nil
	})

	flags.Func("macro", `Macro name to replace (default "__FILELINE__")`, func(s string) error {
		cmd.macro = s
		return checkMacro(s)
	})

	flags.BoolVar(&cmd.verbose, "v", false, "Verbose output")

	err := flags.Parse(args)
	if err == flag.ErrHelp {
		os.Exit(0)
	}

	return &cmd, err
}

// process scans go files in the Cmd directory and replaces macro calls with sequential integers.
// It returns a slice of the FileChange generated by the cmd. Note that the returned changes have not been applied.
func process(cmd *Cmd) (changes []FileChange, err error) {

	debug := func(msg string, args ...any) {
		if cmd.verbose {
			fmt.Printf(msg, args...)
		}
	}

	// collect all go files in dir
	debug("collecting files in %s\n", cmd.dir)
	var files []string
	err = filepath.WalkDir(cmd.dir, func(path string, filemeta fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		// we are not recursing into subdirectories
		if !filemeta.IsDir() && filepath.Dir(path) == cmd.dir && filepath.Ext(path) == ".go" {
			debug("found file %s\n", path)
			files = append(files, path)
		}
		return nil
	})
	if err != nil {
		debug("Failed walking directory %s\n", cmd.dir)
		return changes, fmt.Errorf("Error walking directory %w", err)
	}

	if 0 == len(files) {
		debug("did not encounter any files, exiting\n")
		return changes, err
	}

	count := 1

	// Regex to match MACRO(integer_literal)
	re := regexp.MustCompile(fmt.Sprintf(`%s\(\s*%s\s*\)`, cmd.macro, intLiteral))

	// Process each file
	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			debug("Error reading file %s\n", cmd.dir)
			return changes, fmt.Errorf("Error reading file %w", err)
		}

		// Replace all matches with incremented count
		originalContent := string(content)
		count0 := count
		newContent := re.ReplaceAllStringFunc(originalContent, func(match string) string {
			replacement := fmt.Sprintf("%s(%d)", cmd.macro, count)
			count++
			return replacement
		})

		// Record file changes if any
		if newContent != originalContent {
			debug("performed %d substitutions on file %s\n", (count - count0), file)
			changes = append(changes, FileChange{path: file, content: newContent})
		}
	}

	fmt.Printf("%s: processed %d files, replaced %d %s macros\n", cmd.prog, len(files), count-1, cmd.macro)

	return changes, err
}

func main() {
	cmd, err := parseFlags(os.Args[0], os.Args[1:])
	if nil != err {
		log.Fatalf("failed to parse flags, got error %v", err)
	}
	changes, err := process(cmd)
	if nil != err {
		log.Fatalf("failed processing %s, got error %v", cmd.dir, err)
	}
	for _, change := range changes {
		err = os.WriteFile(change.path, []byte(change.content), 0644)
		fmt.Printf("saving changed %s\n", change.path)
		if nil != err {
			log.Fatalf("failed saving changed %s, got error %v", change.path, err)
		}
	}
}
