package raised

import (
	"testing"
)

func TestSentinel_NoCode(t *testing.T) {
	msg := "something went wrong"
	s := NewSentinel(msg)

	if s.Code() != 0 {
		t.Errorf("expected Code() == 0, got %d", s.Code())
	}
	if s.Error() != msg {
		t.Errorf("expected Error() == %q, got %q", msg, s.Error())
	}
}

func TestSentinel_WithCode(t *testing.T) {
	s := NewSentinel("ERROR(42) something went wrong")

	if s.Code() != 42 {
		t.Errorf("expected Code() == 42, got %d", s.Code())
	}
	want := "ERROR(42) something went wrong"
	if s.Error() != want {
		t.Errorf("expected Error() == %q, got %q", want, s.Error())
	}
}

func TestSentinel_WithNegativeCode(t *testing.T) {
	s := NewSentinel("ERROR(-1) negative code")

	if s.Code() != -1 {
		t.Errorf("expected Code() == -1, got %d", s.Code())
	}
	want := "ERROR(-1) negative code"
	if s.Error() != want {
		t.Errorf("expected Error() == %q, got %q", want, s.Error())
	}
}

func TestSentinel_WithUnderscores(t *testing.T) {
	s := NewSentinel("ERROR(1_000_000) large code")

	if s.Code() != 1000000 {
		t.Errorf("expected Code() == 1000000, got %d", s.Code())
	}
	want := "ERROR(1000000) large code"
	if s.Error() != want {
		t.Errorf("expected Error() == %q, got %q", want, s.Error())
	}
}

func TestSentinel_WithTrailingUnderscore(t *testing.T) {
	// ERROR(n_) is the pattern used by the CLI code generator to mark
	// autogenerated codes with a class prefix; the trailing underscore
	// must be stripped like any other underscore separator.
	s := NewSentinel("ERROR(10_) autogenerated code")

	if s.Code() != 10 {
		t.Errorf("expected Code() == 10, got %d", s.Code())
	}
	want := "ERROR(10) autogenerated code"
	if s.Error() != want {
		t.Errorf("expected Error() == %q, got %q", want, s.Error())
	}
}

func TestSentinel_LeadingTrailingWhitespace(t *testing.T) {
	s := NewSentinel("  ERROR(5): strip whitespace    ")

	if s.Code() != 5 {
		t.Errorf("expected Code() == 5, got %d", s.Code())
	}
	want := "ERROR(5): strip whitespace"
	if s.Error() != want {
		t.Errorf("expected Error() == %q, got %q", want, s.Error())
	}
}

func TestSentinel_CodeZero(t *testing.T) {
	s := NewSentinel("ERROR(0) explicit zero")

	if s.Code() != 0 {
		t.Errorf("expected Code() == 0, got %d", s.Code())
	}
	want := "ERROR(0) explicit zero"
	if s.Error() != want {
		t.Errorf("expected Error() == %q, got %q", want, s.Error())
	}
}

func TestSentinel_ErrorInterface(t *testing.T) {
	// compile-time check that NewSentinel returns a valid SentinelError
	var _ SentinelError = NewSentinel("ERROR(1) interface check")
}
